services:
  file-storage:
    container_name: file-storage
    networks:
      - libsql_storage-network
    environment:
      - PORT=${PORT}
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_AUTH_TOKEN=${DATABASE_AUTH_TOKEN}
      - STORAGE_BASE_PATH=/app/storage
    ports:
      - 80:3000
    volumes:
      - file_storage:/app/storage
    build:
      context: .
      dockerfile: Dockerfile
networks:
  libsql_storage-network:
    external: true
    name: libsql_storage-network
volumes:
  file_storage:
    name: file_stroage
    driver: local
